GridLayout:
    cols: 1
    Label:
        id: titulo
        text: "---> TODO LIST"
    Label:
        text: " - Trabalho de meio ambiente (novo e antigo)"
	Label:
        text: " - Abrir processo do IDUFF"
	Label:
		text: "- Estudar como ser Freelancer"
    Label:
        text: " - Estudar Calculo 2"
    
    Label:
        text: " -  Tutorial Kivy + exercicios + Projeto"

    Label:
        text: " - 100 Days of Code"
	Label:
		text: " - Estudar C++ e Python Juntos."